# Generated by Django 6.0.7 on 2026-07-14 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Password must contain at least 8 characters and no spaces', regex='^\\S{8,}$')]),
        ),
    ]
